/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.68.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BudgetDetailResponse;
import com.konfigthis.client.model.BudgetSettingsResponse;
import com.konfigthis.client.model.BudgetSummaryResponse;
import com.konfigthis.client.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BudgetsApi
 */
@Disabled
public class BudgetsApiTest {

    private static BudgetsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BudgetsApi(apiClient);
    }

    /**
     * Single budget
     *
     * Returns a single budget with all related entities.  This resource is effectively a full budget export.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBudgetTest() throws ApiException {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        BudgetDetailResponse response = api.getBudget(budgetId)
                .lastKnowledgeOfServer(lastKnowledgeOfServer)
                .execute();
        // TODO: test validations
    }

    /**
     * Budget Settings
     *
     * Returns settings for a budget
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSettingsTest() throws ApiException {
        String budgetId = null;
        BudgetSettingsResponse response = api.getSettings(budgetId)
                .execute();
        // TODO: test validations
    }

    /**
     * List budgets
     *
     * Returns budgets list with summary information
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSummaryTest() throws ApiException {
        Boolean includeAccounts = null;
        BudgetSummaryResponse response = api.listSummary()
                .includeAccounts(includeAccounts)
                .execute();
        // TODO: test validations
    }

}
