/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.68.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ErrorResponse;
import com.konfigthis.client.model.PayeeLocationResponse;
import com.konfigthis.client.model.PayeeLocationsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PayeeLocationsApi
 */
@Disabled
public class PayeeLocationsApiTest {

    private static PayeeLocationsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PayeeLocationsApi(apiClient);
    }

    /**
     * Single payee location
     *
     * Returns a single payee location
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSingleTest() throws ApiException {
        String budgetId = null;
        String payeeLocationId = null;
        PayeeLocationResponse response = api.getSingle(budgetId, payeeLocationId)
                .execute();
        // TODO: test validations
    }

    /**
     * List payee locations
     *
     * Returns all payee locations
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllTest() throws ApiException {
        String budgetId = null;
        PayeeLocationsResponse response = api.listAll(budgetId)
                .execute();
        // TODO: test validations
    }

    /**
     * List locations for a payee
     *
     * Returns all payee locations for a specified payee
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listByPayeeTest() throws ApiException {
        String budgetId = null;
        String payeeId = null;
        PayeeLocationsResponse response = api.listByPayee(budgetId, payeeId)
                .execute();
        // TODO: test validations
    }

}
