/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.68.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ErrorResponse;
import com.konfigthis.client.model.ScheduledTransactionResponse;
import com.konfigthis.client.model.ScheduledTransactionsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScheduledTransactionsApi
 */
@Disabled
public class ScheduledTransactionsApiTest {

    private static ScheduledTransactionsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ScheduledTransactionsApi(apiClient);
    }

    /**
     * Single scheduled transaction
     *
     * Returns a single scheduled transaction
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSingleScheduledTransactionTest() throws ApiException {
        String budgetId = null;
        String scheduledTransactionId = null;
        ScheduledTransactionResponse response = api.getSingleScheduledTransaction(budgetId, scheduledTransactionId)
                .execute();
        // TODO: test validations
    }

    /**
     * List scheduled transactions
     *
     * Returns all scheduled transactions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllTest() throws ApiException {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        ScheduledTransactionsResponse response = api.listAll(budgetId)
                .lastKnowledgeOfServer(lastKnowledgeOfServer)
                .execute();
        // TODO: test validations
    }

}
