/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.68.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ErrorResponse;
import com.konfigthis.client.model.ExistingTransaction;
import com.konfigthis.client.model.HybridTransactionsResponse;
import java.time.LocalDate;
import com.konfigthis.client.model.NewTransaction;
import com.konfigthis.client.model.PatchTransactionsWrapper;
import com.konfigthis.client.model.PostTransactionsWrapper;
import com.konfigthis.client.model.PutTransactionWrapper;
import com.konfigthis.client.model.SaveTransactionWithIdOrImportId;
import com.konfigthis.client.model.SaveTransactionsResponse;
import com.konfigthis.client.model.TransactionResponse;
import com.konfigthis.client.model.TransactionsImportResponse;
import com.konfigthis.client.model.TransactionsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionsApi
 */
@Disabled
public class TransactionsApiTest {

    private static TransactionsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TransactionsApi(apiClient);
    }

    /**
     * Create a single transaction or multiple transactions
     *
     * Creates a single transaction or multiple transactions.  If you provide a body containing a &#x60;transaction&#x60; object, a single transaction will be created and if you provide a body containing a &#x60;transactions&#x60; array, multiple transactions will be created.  Scheduled transactions cannot be created on this endpoint.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSingleOrMultipleTest() throws ApiException {
        String budgetId = null;
        NewTransaction transaction = null;
        List<NewTransaction> transactions = null;
        SaveTransactionsResponse response = api.createSingleOrMultiple(budgetId)
                .transaction(transaction)
                .transactions(transactions)
                .execute();
        // TODO: test validations
    }

    /**
     * Deletes an existing transaction
     *
     * Deletes a transaction
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteExistingTransactionTest() throws ApiException {
        String budgetId = null;
        String transactionId = null;
        TransactionResponse response = api.deleteExistingTransaction(budgetId, transactionId)
                .execute();
        // TODO: test validations
    }

    /**
     * Single transaction
     *
     * Returns a single transaction
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSingleTransactionTest() throws ApiException {
        String budgetId = null;
        String transactionId = null;
        TransactionResponse response = api.getSingleTransaction(budgetId, transactionId)
                .execute();
        // TODO: test validations
    }

    /**
     * Import transactions
     *
     * Imports available transactions on all linked accounts for the given budget.  Linked accounts allow transactions to be imported directly from a specified financial institution and this endpoint initiates that import.  Sending a request to this endpoint is the equivalent of clicking \&quot;Import\&quot; on each account in the web application or tapping the \&quot;New Transactions\&quot; banner in the mobile applications.  The response for this endpoint contains the transaction ids that have been imported.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importLinkedAccountsTest() throws ApiException {
        String budgetId = null;
        TransactionsImportResponse response = api.importLinkedAccounts(budgetId)
                .execute();
        // TODO: test validations
    }

    /**
     * List account transactions
     *
     * Returns all transactions for a specified account
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listByAccountTest() throws ApiException {
        String budgetId = null;
        String accountId = null;
        LocalDate sinceDate = null;
        String type = null;
        Long lastKnowledgeOfServer = null;
        TransactionsResponse response = api.listByAccount(budgetId, accountId)
                .sinceDate(sinceDate)
                .type(type)
                .lastKnowledgeOfServer(lastKnowledgeOfServer)
                .execute();
        // TODO: test validations
    }

    /**
     * List category transactions
     *
     * Returns all transactions for a specified category
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listByCategoryTest() throws ApiException {
        String budgetId = null;
        String categoryId = null;
        LocalDate sinceDate = null;
        String type = null;
        Long lastKnowledgeOfServer = null;
        HybridTransactionsResponse response = api.listByCategory(budgetId, categoryId)
                .sinceDate(sinceDate)
                .type(type)
                .lastKnowledgeOfServer(lastKnowledgeOfServer)
                .execute();
        // TODO: test validations
    }

    /**
     * List payee transactions
     *
     * Returns all transactions for a specified payee
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listByPayeeTest() throws ApiException {
        String budgetId = null;
        String payeeId = null;
        LocalDate sinceDate = null;
        String type = null;
        Long lastKnowledgeOfServer = null;
        HybridTransactionsResponse response = api.listByPayee(budgetId, payeeId)
                .sinceDate(sinceDate)
                .type(type)
                .lastKnowledgeOfServer(lastKnowledgeOfServer)
                .execute();
        // TODO: test validations
    }

    /**
     * List transactions
     *
     * Returns budget transactions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTransactionsTest() throws ApiException {
        String budgetId = null;
        LocalDate sinceDate = null;
        String type = null;
        Long lastKnowledgeOfServer = null;
        TransactionsResponse response = api.listTransactions(budgetId)
                .sinceDate(sinceDate)
                .type(type)
                .lastKnowledgeOfServer(lastKnowledgeOfServer)
                .execute();
        // TODO: test validations
    }

    /**
     * Updates an existing transaction
     *
     * Updates a single transaction
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateExistingTransactionTest() throws ApiException {
        ExistingTransaction transaction = null;
        String budgetId = null;
        String transactionId = null;
        TransactionResponse response = api.updateExistingTransaction(transaction, budgetId, transactionId)
                .execute();
        // TODO: test validations
    }

    /**
     * Update multiple transactions
     *
     * Updates multiple transactions, by &#x60;id&#x60; or &#x60;import_id&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateMultipleTest() throws ApiException {
        List<SaveTransactionWithIdOrImportId> transactions = null;
        String budgetId = null;
        SaveTransactionsResponse response = api.updateMultiple(transactions, budgetId)
                .execute();
        // TODO: test validations
    }

}
